inherit_from: .rubocop_todo.yml

inherit_gem:
  betterlint:
    - config/default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.2
  Exclude:
    - gemfiles/*.gemfile
